### ISSUE TITLE
Tools for the annotated paper

### ISSUE THREAD

**Issue by JiahaoYao** [AakashKumarNain/annotated_research_papers#3]
Hi Aakash, 

   Really like this repo, could you please tell me what tool you are using for making these?

**Comment by Nikronic** [comment]
Hi @JiahaoYao 
Actually, I like to annotate papers based on different factors and because of that, using different tools like highlighter, underline, pen drawing, rectangles, notes, inserting images, etc helps me a lot.
After a thorough searching, I found Xodo PDF as the best free annotator. The paid alternative is Wondershare PDFelement. I also used Foxit Phantom PDF and Adobe Acrobat DC, but none of them are good for annotating.
Xodo PDF is available on all platforms, so it is a good choice.
Even though PDFelement has excellent tools, but it increases files sizes too much. For instance, annotating a chapter of a book increased the size from 15mb to 60mb, meanwhile Xodo does not increase the size more than 10% even on highly annotated file. The reason that I wrote this is that I think @AakashKumarNain is using PDFelement too.

Note that I only considered speed and easy access to the annotation tools as the comparison factor. 

Please let me know if you have a better option!

EDIT (4 years later!): Now I use Xodo on mobile, and Okular on PC. Okular is very lightweight and has many tools for highlighting. The best part is that it supports keyboard shortcuts, so you can switch tools very fast.

**Comment by JiahaoYao** [comment]
Great, thanks for your detailed answer! Appreciate it!

**Comment by AakashKumarNain** [comment]
Thank you @JiahaoYao and @Nikronic . I use `Notability` for annotating but as @Nikronic the size increases rapidly with more annotations.

**Comment by NirobNabil** [comment]
@JiahaoYao I settled with `notewise`. it provides much more versatility when using a stylus, ui is minimal, doesn't let you edit pdf texts but lets you add extra pages so that you can write your own detailed notes or derivations. It doesn't have the file size increase issue and its also cheaper than pdfelement at only about 2.5$ a month.
